/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CategorySchema extends BaseModel {
  static $columns = ['archived', 'color', 'createdAt', 'icon', 'id', 'name', 'sortOrder', 'updatedAt', 'workspaceId'] as const
  $columns = CategorySchema.$columns
  @column()
  declare archived: boolean
  @column()
  declare color: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare icon: string | null
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare name: string
  @column()
  declare sortOrder: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare workspaceId: bigint | number | null
}

export class ItemSchema extends BaseModel {
  static $columns = ['categoryId', 'createdAt', 'defaultAmount', 'id', 'isActive', 'kind', 'name', 'sortOrder', 'updatedAt', 'workspaceId'] as const
  $columns = ItemSchema.$columns
  @column()
  declare categoryId: bigint | number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare defaultAmount: string | null
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare isActive: boolean
  @column()
  declare kind: string
  @column()
  declare name: string
  @column()
  declare sortOrder: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare workspaceId: bigint | number | null
}

export class MonthlyEntrySchema extends BaseModel {
  static $columns = ['amount', 'createdAt', 'id', 'itemId', 'month', 'note', 'paidAt', 'status', 'updatedAt', 'workspaceId', 'year'] as const
  $columns = MonthlyEntrySchema.$columns
  @column()
  declare amount: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare itemId: bigint | number | null
  @column()
  declare month: number
  @column()
  declare note: string | null
  @column.dateTime()
  declare paidAt: DateTime | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare workspaceId: bigint | number | null
  @column()
  declare year: number
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class WorkspaceSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'ownerUserId', 'updatedAt'] as const
  $columns = WorkspaceSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare name: string
  @column()
  declare ownerUserId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class WorkspaceMemberSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'role', 'updatedAt', 'userId', 'workspaceId'] as const
  $columns = WorkspaceMemberSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
  @column()
  declare workspaceId: bigint | number | null
}
