/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CategorySchema extends BaseModel {
  static $columns = ['archived', 'color', 'createdAt', 'icon', 'id', 'name', 'sortOrder', 'updatedAt', 'workspaceId'] as const
  $columns = CategorySchema.$columns
  @column()
  declare archived: boolean
  @column()
  declare color: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare icon: string | null
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare name: string
  @column()
  declare sortOrder: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare workspaceId: bigint | number | null
}

export class ItemSchema extends BaseModel {
  static $columns = ['autoSource', 'categoryId', 'createdAt', 'defaultAmount', 'id', 'installmentsPaid', 'installmentsTotal', 'isActive', 'kind', 'name', 'sortOrder', 'updatedAt', 'workspaceId'] as const
  $columns = ItemSchema.$columns
  @column()
  declare autoSource: string | null
  @column()
  declare categoryId: bigint | number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare defaultAmount: string | null
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare installmentsPaid: number | null
  @column()
  declare installmentsTotal: number | null
  @column()
  declare isActive: boolean
  @column()
  declare kind: string
  @column()
  declare name: string
  @column()
  declare sortOrder: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare workspaceId: bigint | number | null
}

export class MonthlyEntrySchema extends BaseModel {
  static $columns = ['amount', 'createdAt', 'id', 'itemId', 'month', 'note', 'paidAt', 'status', 'updatedAt', 'workspaceId', 'year'] as const
  $columns = MonthlyEntrySchema.$columns
  @column()
  declare amount: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare itemId: bigint | number | null
  @column()
  declare month: number
  @column()
  declare note: string | null
  @column.dateTime()
  declare paidAt: DateTime | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare workspaceId: bigint | number | null
  @column()
  declare year: number
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class WorkspaceSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'ownerUserId', 'updatedAt'] as const
  $columns = WorkspaceSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare name: string
  @column()
  declare ownerUserId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class WorkspaceMemberSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'role', 'updatedAt', 'userId', 'workspaceId'] as const
  $columns = WorkspaceMemberSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
  @column()
  declare workspaceId: bigint | number | null
}

export class ReserveAccountSchema extends BaseModel {
  static $columns = ['archived', 'color', 'createdAt', 'goalAmount', 'goalDate', 'goalMonthlyContribution', 'id', 'institution', 'lastClosedPeriod', 'name', 'openedAt', 'sortOrder', 'updatedAt', 'workspaceId'] as const
  $columns = ReserveAccountSchema.$columns
  @column()
  declare archived: boolean
  @column()
  declare color: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare goalAmount: string | null
  @column.date()
  declare goalDate: DateTime | null
  @column()
  declare goalMonthlyContribution: string | null
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare institution: string | null
  @column()
  declare lastClosedPeriod: string | null
  @column()
  declare name: string
  @column.date()
  declare openedAt: DateTime
  @column()
  declare sortOrder: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare workspaceId: bigint | number | null
}

export class ReserveRatePeriodSchema extends BaseModel {
  static $columns = ['createdAt', 'effectiveMonth', 'effectiveYear', 'id', 'rateKind', 'rateValue', 'reserveAccountId', 'updatedAt', 'workspaceId'] as const
  $columns = ReserveRatePeriodSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare effectiveMonth: number
  @column()
  declare effectiveYear: number
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare rateKind: string
  @column()
  declare rateValue: string
  @column()
  declare reserveAccountId: bigint | number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare workspaceId: bigint | number | null
}

export class ReserveMovementSchema extends BaseModel {
  static $columns = ['amount', 'createdAt', 'description', 'id', 'kind', 'occurredOn', 'reserveAccountId', 'updatedAt', 'workspaceId', 'yieldBase', 'yieldCdiAnnual', 'yieldPeriod', 'yieldRateApplied', 'yieldRateKind', 'yieldRateSource'] as const
  $columns = ReserveMovementSchema.$columns
  @column()
  declare amount: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare kind: string
  @column.date()
  declare occurredOn: DateTime
  @column()
  declare reserveAccountId: bigint | number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare workspaceId: bigint | number | null
  @column()
  declare yieldBase: string | null
  @column()
  declare yieldCdiAnnual: string | null
  @column()
  declare yieldPeriod: string | null
  @column()
  declare yieldRateApplied: string | null
  @column()
  declare yieldRateKind: string | null
  @column()
  declare yieldRateSource: string | null
}

export class CdiRateSchema extends BaseModel {
  static $columns = ['annualRate', 'createdAt', 'id', 'month', 'updatedAt', 'workspaceId', 'year'] as const
  $columns = CdiRateSchema.$columns
  @column()
  declare annualRate: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare month: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare workspaceId: bigint | number | null
  @column()
  declare year: number
}

export class VariableExpenseSchema extends BaseModel {
  static $columns = ['amount', 'categoryId', 'createdAt', 'description', 'id', 'spentOn', 'updatedAt', 'workspaceId'] as const
  $columns = VariableExpenseSchema.$columns
  @column()
  declare amount: string
  @column()
  declare categoryId: bigint | number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: bigint | number
  @column.date()
  declare spentOn: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare workspaceId: bigint | number | null
}
